name: loginTodo Publish

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Setting environment variables
        run: echo "REACT_APP_BASE_URL=$REACT_APP_BASE_URL" >> .env.production
        env:
          REACT_APP_BASE_URL: ${{secrets.REACT_APP_BASE_URL}}

      - name: Install npm package
        run: npm install

      - name: Build Pages
        run: npm run build

      - name: publish gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.TODO }}
          publish_dir: ./build
